function [vls]=plotchoice
    d = dialog('Position',[800 300 250 400],...
        'Name','Design Space');

    txt = uicontrol('Parent',d,...
        'Style','text',...
        'Position',[20 340 210 40],...
        'String','Check Design Parameters to include');
    
    btn1 = uicontrol('Parent',d,...
        'Style','checkbox',...
        'Position',[85 300 150 25],...
        'String','Power Requried',...
        'Value',1);
    
    btn2 = uicontrol('Parent',d,...
        'Style','checkbox',...
        'Position',[85 250 150 25],...
        'String','Attack Angle');
    
    btn3 = uicontrol('Parent',d,...
        'Style','checkbox',...
        'Position',[85 200 150 25],...
        'String','Fuel Efficiency',...
        'Value',1);
    
    btn4 = uicontrol('Parent',d,...
        'Style','checkbox',...
        'Position',[85 150 150 25],...
        'String','L/D Lines');
    
    btn5 = uicontrol('Parent',d,...
        'Style','checkbox',...
        'Position',[85 100 150 25],...
        'String','N-Turns');
    
    btn6 = uicontrol('Parent',d,...
        'Style','checkbox',...
        'Position',[85 50 150 25],...
        'String','250&300 mph lines',...
        'Value',1);
    
    uicontrol('Parent',d,...
        'Position',[85 10 70 25],...
        'String','Execute',...
        'Callback',@vlupdate);
    
    function vlupdate(src,cllbck)
        vls=[get([btn1,btn2,btn3,btn4,btn5,btn6],'Value')];
        delete(gcf)
    end
    waitfor(d)
end